version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/social-sample-server
permissions:
  - object: /home/ec2-user/social-sample-server
    owner: ec2-user
    group: ec2-user
    mode: 755